import type { CatalogDescriptor } from './parser.types';

const descriptors: Record<string, CatalogDescriptor> = {
  skills: {
    scope: 'skills',
    label: 'Skills',
    sheetName: 'Skills',
    exampleRow: { id: 'skl_first_aid', name: 'First Aid', description: 'Basic first aid training', status: 'active' },
    columns: [
      { key: 'id', header: 'id', required: false, aliases: ['skill_id'], notes: 'Auto si vacío' },
      { key: 'name', header: 'name', required: true, type: 'string' },
      { key: 'description', header: 'description', required: false, type: 'string' },
      { key: 'status', header: 'status', required: true, type: 'enum', enumValues: ['active', 'inactive', 'archived'], example: 'active' },
    ],
  },
  'worker-roles': {
    scope: 'worker-roles',
    label: 'Worker Roles',
    sheetName: 'WorkerRoles',
    exampleRow: { id: 'wrl_operator', name: 'Operator', description: 'Heavy equipment operator', status: 'active' },
    columns: [
      { key: 'id', header: 'id', required: false, aliases: ['role_id'] },
      { key: 'name', header: 'name', required: true, type: 'string' },
      { key: 'description', header: 'description', required: false, type: 'string' },
      { key: 'status', header: 'status', required: true, type: 'enum', enumValues: ['active', 'inactive', 'archived'], example: 'active' },
    ],
  },
  'project-types': {
    scope: 'project-types',
    label: 'Project Types',
    sheetName: 'ProjectTypes',
    exampleRow: { id: 'pt_construction', name: 'Construction', description: 'Construction project', status: 'active' },
    columns: [
      { key: 'id', header: 'id', required: false, aliases: ['project_type_id'] },
      { key: 'name', header: 'name', required: true, type: 'string' },
      { key: 'description', header: 'description', required: false, type: 'string' },
      { key: 'status', header: 'status', required: true, type: 'enum', enumValues: ['active', 'inactive', 'archived'], example: 'active' },
    ],
  },
  projects: {
    scope: 'projects',
    label: 'Projects',
    sheetName: 'Projects',
    exampleRow: {
      id: 'prj_1700',
      number: '1700',
      name: 'PG&E Infrastructure Services',
      clientId: 'cli_acme',
      clientName: 'Acme Corp',
      projectTypeId: 'pt_construction',
      projectTypeName: 'Construction',
      projectManager: 'Michael Thompson',
      projectManagerEmail: 'michael@acme.com',
      location: '1600 Pennsylvania Ave',
      city: 'Redlands',
      state: 'CA',
      zipCode: '92374',
      country: 'USA',
      latitude: 34.0556,
      longitude: -117.1825,
      status: 'active',
      workOrderNumber: 'WO-2026-001',
      purchaseOrder: 'PO-2026-001',
      startDate: '2026-04-07',
      endDate: '2026-04-18',
      description: 'Project description here',
      notes: 'Optional notes here',
    },
    columns: [
      { key: 'id', header: 'id', required: false, aliases: ['project_id'] },
      { key: 'number', header: 'number', required: true, type: 'string', example: '1700', notes: 'Project number (e.g. 1700)' },
      { key: 'name', header: 'name', required: true, type: 'string' },
      { key: 'clientId', header: 'clientId', required: false, type: 'string', aliases: ['client_id'], notes: 'Client ID o clientName' },
      { key: 'clientName', header: 'clientName', required: false, type: 'string', aliases: ['client_name'], notes: 'Se busca por nombre si clientId está vacío' },
      { key: 'projectTypeId', header: 'projectTypeId', required: false, type: 'string', aliases: ['project_type_id'], notes: 'Project type ID o projectTypeName' },
      { key: 'projectTypeName', header: 'projectTypeName', required: false, type: 'string', aliases: ['project_type_name'], notes: 'Se busca por nombre si projectTypeId está vacío' },
      { key: 'projectManager', header: 'projectManager', required: false, type: 'string', aliases: ['project_manager'] },
      { key: 'projectManagerEmail', header: 'projectManagerEmail', required: false, type: 'string', aliases: ['project_manager_email'] },
      { key: 'location', header: 'location', required: false, type: 'string' },
      { key: 'city', header: 'city', required: false, type: 'string' },
      { key: 'state', header: 'state', required: false, type: 'string' },
      { key: 'zipCode', header: 'zipCode', required: false, type: 'string', aliases: ['zip_code', 'zip'] },
      { key: 'country', header: 'country', required: false, type: 'string' },
      { key: 'latitude', header: 'latitude', required: false, type: 'number' },
      { key: 'longitude', header: 'longitude', required: false, type: 'number' },
      { key: 'status', header: 'status', required: true, type: 'string', example: 'active' },
      { key: 'workOrderNumber', header: 'workOrderNumber', required: false, type: 'string', aliases: ['work_order_number'] },
      { key: 'purchaseOrder', header: 'purchaseOrder', required: false, type: 'string', aliases: ['purchase_order'] },
      { key: 'startDate', header: 'startDate', required: false, type: 'date', aliases: ['start_date'] },
      { key: 'endDate', header: 'endDate', required: false, type: 'date', aliases: ['end_date'] },
      { key: 'description', header: 'description', required: false, type: 'string' },
      { key: 'notes', header: 'notes', required: false, type: 'string' },
    ],
  },
  'work-order-types': {
    scope: 'work-order-types',
    label: 'Work Order Types',
    sheetName: 'WorkOrderTypes',
    exampleRow: { id: 'wot_flagging', name: 'Flagging', description: 'Traffic flagging service', status: 'active' },
    columns: [
      { key: 'id', header: 'id', required: false, aliases: ['work_order_type_id'] },
      { key: 'name', header: 'name', required: true, type: 'string' },
      { key: 'description', header: 'description', required: false, type: 'string' },
      { key: 'status', header: 'status', required: true, type: 'enum', enumValues: ['active', 'inactive', 'archived'], example: 'active' },
    ],
  },
  equipment: {
    scope: 'equipment',
    label: 'Equipment',
    sheetName: 'Equipment',
    exampleRow: { id: 'eq_cone_set', name: 'Cone Set 28"', type: 'Traffic Control', identifier: 'CONE-28-001', brand: 'Cortina', status: 'available', lastMaintenance: '2026-01-15', nextMaintenance: '2026-07-15', notes: 'Standard' },
    columns: [
      { key: 'id', header: 'id', required: false, aliases: ['equipment_id'] },
      { key: 'name', header: 'name', required: true, type: 'string' },
      { key: 'type', header: 'type', required: true, type: 'string' },
      { key: 'identifier', header: 'identifier', required: false, type: 'string' },
      { key: 'brand', header: 'brand', required: false, type: 'string' },
      { key: 'status', header: 'status', required: true, type: 'string' },
      { key: 'lastMaintenance', header: 'lastMaintenance', required: false, type: 'date', aliases: ['last_maintenance'] },
      { key: 'nextMaintenance', header: 'nextMaintenance', required: false, type: 'date', aliases: ['next_maintenance'] },
      { key: 'notes', header: 'notes', required: false, type: 'string' },
    ],
  },
  materials: {
    scope: 'materials',
    label: 'Materials',
    sheetName: 'Materials',
    exampleRow: { id: 'mat_sign_aluminum', name: 'Sign Aluminum 48x48', type: 'Signage', identifier: 'SIGN-ALU-48', brand: 'Custom', price: 0, status: 'available', lastMaintenance: '', nextMaintenance: '', notes: '' },
    columns: [
      {
        key: 'id',
        header: 'id',
        required: false,
        aliases: ['internal_id'],
        notes: 'Clave interna opcional',
      },
      { key: 'name', header: 'name', required: true, type: 'string' },
      { key: 'type', header: 'type', required: true, type: 'string' },
      {
        key: 'identifier',
        header: 'identifier',
        required: true,
        type: 'string',
        aliases: ['material_id'],
        notes:
          'Material ID visible; junto con name y type identifica el registro durante la importación',
      },
      { key: 'brand', header: 'brand', required: false, type: 'string' },
      { key: 'price', header: 'price', required: false, type: 'number' },
      { key: 'status', header: 'status', required: true, type: 'string' },
      { key: 'lastMaintenance', header: 'lastMaintenance', required: false, type: 'date', aliases: ['last_maintenance'] },
      { key: 'nextMaintenance', header: 'nextMaintenance', required: false, type: 'date', aliases: ['next_maintenance'] },
      { key: 'notes', header: 'notes', required: false, type: 'string' },
    ],
  },
  certifications: {
    scope: 'certifications',
    label: 'Certifications',
    sheetName: 'Certifications',
    exampleRow: { id: 'cert_osha_10', name: 'OSHA 10', description: 'OSHA 10-hour safety training', status: 'active', documentUrl: 'https://example.com/osha10.pdf' },
    columns: [
      { key: 'id', header: 'id', required: false, aliases: ['certification_id'] },
      { key: 'name', header: 'name', required: true, type: 'string' },
      { key: 'description', header: 'description', required: false, type: 'string' },
      { key: 'status', header: 'status', required: true, type: 'enum', enumValues: ['active', 'inactive', 'archived'], example: 'active' },
      { key: 'documentUrl', header: 'documentUrl', required: false, type: 'string', aliases: ['document_url'], notes: 'URL del documento de la certificación' },
    ],
  },
  'status-catalog': {
    scope: 'status-catalog',
    label: 'Status Catalog',
    sheetName: 'StatusCatalog',
    exampleRow: { id: 'wo_in_progress', scope: 'work_order', value: 'in_progress', name: 'In Progress', color: '#3B82F6', sortOrder: 20, blocksEditing: false, triggersNotification: false, requiresApproval: false, status: 'active' },
    columns: [
      { key: 'id', header: 'id', required: false, aliases: ['status_id'] },
      { key: 'scope', header: 'scope', required: true, type: 'enum', enumValues: ['work_order', 'work_status', 'shift', 'timesheet', 'project', 'equipment', 'availability_request', 'incident', 'form_submission'] },
      { key: 'value', header: 'value', required: true, type: 'string' },
      { key: 'name', header: 'name', required: true, type: 'string' },
      { key: 'color', header: 'color', required: false, type: 'string', example: '#3B82F6' },
      { key: 'sortOrder', header: 'sortOrder', required: false, type: 'number', aliases: ['sort_order'] },
      { key: 'blocksEditing', header: 'blocksEditing', required: false, type: 'boolean', aliases: ['blocks_editing'] },
      { key: 'triggersNotification', header: 'triggersNotification', required: false, type: 'boolean', aliases: ['triggers_notification'] },
      { key: 'requiresApproval', header: 'requiresApproval', required: false, type: 'boolean', aliases: ['requires_approval'] },
      { key: 'status', header: 'status', required: true, type: 'enum', enumValues: ['active', 'inactive'], example: 'active' },
    ],
  },
  'commercial-catalog-items': {
    scope: 'commercial-catalog-items',
    label: 'Commercial Catalog Items',
    sheetName: 'CommercialCatalogItems',
    exampleRow: { sku: 'RNT-CONE-28', description: '28" Traffic Cone rental', type: 'rental', dailyRate: 1.5, itemPrice: 0, unit: 'Each', status: 'active', notes: '' },
    columns: [
      { key: 'id', header: 'id', required: false, aliases: ['item_id'] },
      { key: 'sku', header: 'sku', required: true, type: 'string' },
      { key: 'description', header: 'description', required: true, type: 'string' },
      { key: 'type', header: 'type', required: false, type: 'string' },
      { key: 'dailyRate', header: 'dailyRate', required: true, type: 'number', aliases: ['daily_rate'] },
      { key: 'itemPrice', header: 'itemPrice', required: false, type: 'number', aliases: ['item_price'] },
      { key: 'unit', header: 'unit', required: false, type: 'string' },
      { key: 'status', header: 'status', required: true, type: 'string', example: 'active' },
      { key: 'notes', header: 'notes', required: false, type: 'string' },
    ],
  },
  clients: {
    scope: 'clients',
    label: 'Clients',
    sheetName: 'Clients',
    exampleRow: { id: 'cli_acme', name: 'Acme Corp', contactName: 'John Smith', email: 'ops@acme.com', phone: '+15551234567', website: 'https://acme.com', address: '123 Main St', city: 'Austin', state: 'TX', zipCode: '78701', country: 'USA', latitude: 30.27, longitude: -97.74, status: 'active', notes: '' },
    columns: [
      { key: 'id', header: 'id', required: false, aliases: ['client_id'] },
      { key: 'name', header: 'name', required: true, type: 'string' },
      { key: 'contactName', header: 'contactName', required: false, type: 'string', aliases: ['contact_name'] },
      { key: 'email', header: 'email', required: false, type: 'string' },
      { key: 'phone', header: 'phone', required: false, type: 'string' },
      { key: 'website', header: 'website', required: false, type: 'string' },
      { key: 'address', header: 'address', required: false, type: 'string' },
      { key: 'city', header: 'city', required: false, type: 'string' },
      { key: 'state', header: 'state', required: false, type: 'string' },
      { key: 'zipCode', header: 'zipCode', required: false, type: 'string', aliases: ['zip_code', 'zip'] },
      { key: 'country', header: 'country', required: false, type: 'string' },
      { key: 'latitude', header: 'latitude', required: false, type: 'number' },
      { key: 'longitude', header: 'longitude', required: false, type: 'number' },
      { key: 'status', header: 'status', required: true, type: 'string', example: 'active' },
      { key: 'notes', header: 'notes', required: false, type: 'string' },
    ],
  },
  workers: {
    scope: 'workers',
    label: 'Workers',
    sheetName: 'Workers',
    exampleRow: { id: 'wkr_jdoe', firstName: 'Jane', lastName: 'Doe', email: 'jane.doe@example.com', phone: '+15125550100', type: 'Flagger', role: 'Operator', status: 'active', hireDate: '2024-03-01', hourlyRate: 22.5, city: 'Austin', state: 'TX', country: 'USA', skills: 'first aid, traffic control', workerRoles: 'operator', certifications: 'OSHA 10' },
    supportsAsync: true,
    columns: [
      { key: 'id', header: 'id', required: false, aliases: ['worker_id'] },
      { key: 'firstName', header: 'firstName', required: true, aliases: ['first_name'] },
      { key: 'lastName', header: 'lastName', required: true, aliases: ['last_name'] },
      { key: 'email', header: 'email', required: true, type: 'string' },
      { key: 'phone', header: 'phone', required: true, type: 'string' },
      { key: 'driverLicense', header: 'driverLicense', required: false, aliases: ['driver_license'] },
      { key: 'driverLicenseExpiration', header: 'driverLicenseExpiration', required: false, type: 'date', aliases: ['driver_license_expiration'] },
      { key: 'primaryAddress', header: 'primaryAddress', required: false, aliases: ['address', 'primary_address'] },
      { key: 'city', header: 'city', required: false, type: 'string' },
      { key: 'zipCode', header: 'zipCode', required: false, aliases: ['zip_code', 'zip'] },
      { key: 'state', header: 'state', required: false, type: 'string' },
      { key: 'country', header: 'country', required: false, type: 'string' },
      { key: 'latitude', header: 'latitude', required: false, type: 'number' },
      { key: 'longitude', header: 'longitude', required: false, type: 'number' },
      { key: 'type', header: 'type', required: true, type: 'string' },
      { key: 'role', header: 'role', required: true, type: 'string' },
      { key: 'status', header: 'status', required: true, type: 'string', example: 'active' },
      { key: 'hireDate', header: 'hireDate', required: false, type: 'date', aliases: ['hire_date'] },
      { key: 'hourlyRate', header: 'hourlyRate', required: true, type: 'number', aliases: ['hourly_rate'] },
      { key: 'emergencyContact', header: 'emergencyContact', required: false, aliases: ['emergency_contact'] },
      { key: 'notes', header: 'notes', required: false, type: 'string' },
      { key: 'skills', header: 'skills', required: false, type: 'csv', notes: 'Nombres separados por coma' },
      { key: 'workerRoles', header: 'workerRoles', required: false, type: 'csv', aliases: ['roles'], notes: 'Nombres separados por coma' },
      { key: 'certifications', header: 'certifications', required: false, type: 'csv', notes: 'Nombres separados por coma' },
    ],
  },
};

export function getDescriptor(scope: keyof typeof descriptors): CatalogDescriptor {
  const d = descriptors[scope];
  if (!d) throw new Error(`Unknown scope: ${scope}`);
  return d;
}

export function listDescriptors(): CatalogDescriptor[] {
  return Object.values(descriptors);
}
